### ISSUE TITLE
Datasets with composite products VS datasets with imagery

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/veda-ui#45]
It is planned to have datasets available in two different flavors.

⚠️ Nomenclature is still a bit fuzzy. @leothomas @anayeaye if you know better/official names for these let us know.

## Composite products
Defined by a product that was already processed and is shown to the user with several variations. An example would be "NO2" or "CIMP6".
The different variations are available in the form of layers that can be seen on the map and may have compare options.

__🤓 In STAC terms this means that the user can see different collections.__

<table width="100%">
<tr>
<th><img width="441" height="1">Interface</th>
<th><img width="441" height="1">Dataset configuration</th>
</tr>
<tr>
<td>

![image](https://user-images.githubusercontent.com/1090606/157409550-b84c940c-27fe-450c-8185-639bfb4ff739.png)

</td>
<td>

```yml
id: no2
name: Nitrogen Dioxide
layers:
  - id: no2-monthly
    name: Avg
    ...
  - id: no2-diff
    name: Diff
    ...
```

</td>
</tr>
</table>

## Imagery
Defined by "raw satellite imagery" whose different bands can be manipulated. An example could be "Landsat 8" data.
In this dataset the user can only explore one layer, but can view it in different ways by changing the bands.

__🤓 In STAC terms this means that the user can see only 1 collection tiles according to the provided band params.__

<table>
  <tr>
    <th>Interface</th>
    <th>Dataset configuration</th>
  </tr>
<tr>
<td>

![image](https://user-images.githubusercontent.com/1090606/157411816-a097c316-e20f-441f-b0ec-22bafa22a187.png)

</td>
<td width='50'>

We still have to think about how to configure a dataset that is showing an imagery layer, but could be something along these lines:

```yml
id: ls8
name: Landsat 8

layer:
  # Id needed for the stac collection
  id: landsat8
  # Different presets chosen from a list of options.
  # These are shown in the interface alongside "Custom"
  presets:
    - natural
    - false-color
```

</td>
</tr>
</table>

@ricardoduplos does this capture the conversation we had yesterday. cc @olafveerman 

@leothomas @anayeaye Does this make sense backend wise?
