### ISSUE TITLE
Handle taxonomies

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/veda-ui#510]
After the removal of thematic areas and the addition of "soruces" as a data catalog filter, we need to figure out how to handle these taxonomies and have a human readable name.

An index with all the taxonomies could be an option

**Comment by danielfdsilva** [comment]
After a conversation with @nerik we decided that having a taxonomies index file was the best option as it allows us to store additional properties if needed.

Example:
```yml
# taxonomies.yml

topics:
  - id:
    name:

sources:
  - id:
    name:
    url:
    logo:
```

The veda resolver will load the data and make it available on each discovery and dataset.
