### ISSUE TITLE
Allow for customization of data catalog filters

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/veda-ui#573]
From discussion on: https://github.com/NASA-IMPACT/veda-architecture/issues/273

Each instance should be able to define what filters are available in the data catalog page based on dataset properties.
Filtering will be done on a direct property matching basis, without complex logic.

### Automatically inferred
This option would have the users add values under a specific key in the dataset frontmatter (eg. `taxonomy`). The app would then gather all unique values and build a filtering system.  

```yml
taxonomy:
  Sector:
    - Agriculture, Forestry and Land Use
    - Energy
  Producer:
    - NIST
  Gas Emission:
  -   COx
```

**pros & cons** 
- 💚 No need to have filters defined elsewhere
- 💚 Easily readable
- 💔 Prone to error, given that users have to spell the filter name exactly

### Manual definition
This option requires the users to specify the the filter keys and labels in a separate file, besides adding the values to a dataset frontmatter.

```js
filters = {
  sector: {
    label: 'Sector',
    key: `sector`,
    options : [] // Could be implemented to offer option validation
  },
  gas: {
    label: 'Gas Emission',
    key: `gas-emission`,
  }
}
```
On the dataset
```yml
id: dataset id
name: Some name
sector: Energy
gas-emission: COx
```

**pros & cons** 
- 💚 No need to rely on a specific dataset key to hold all values
- 💚 Allows for values to be validated if array of options is provided
- 💔 Requires maintenance of taxonomy source
- 💔💚 Requires users to check file to know the keys, but it is less error prone

## Design

The current UI does not accommodate a growing list of filters and has a pretty low hard limit.  
We need to find a way to ensure a higher number of filters is supported.

<img width="1350" alt="image" src="https://github.com/NASA-IMPACT/veda-ui/assets/1090606/d7d27ef1-7f4c-4345-9817-960dccb3eabd">

## Tasks
_besides technical implementation_

- [ ] Comment on approach @danielfdsilva @hanbyul-here @nerik (feel free to provide other options)
- [ ] Figure out way to accomodate more filters @ricardoduplos @faustoperez

**Comment by hanbyul-here** [comment]
More related to the original issue: It could be from my ignorance, but can we add this taxonomy metadata to the searchable metadata so we don't need an unexpected number of dropdowns on the page? My preference for searching is always just a plain text search + no limit on the level of taxonomies sounds like it can become chaotic fast. 
If we add something like the below in the dataset metadata, and text search would return this dataset when user types 'NIST' 
```yml
...

taxonomy:
  Sector:
    - Agriculture, Forestry and Land Use
    - Energy
  Producer:
    - NIST
  Gas Emission:
  -   COx
```

related to this issue: I think the first approach is more aligned with how Veda handles with thematic now. It will be nice to add the validation step to check typos and mistakes in the building process.
